import Head from 'next/head'

import AppLayout from '../components/AppLayout'
import Button from '../components/Button'
import GitHubIcon from '../components/Icons/GitHubIcon'
import { logingWithFacebook } from '../firebase/client'
import { colors } from '../styles/Theme'




export default function Home() {

  const handleLoginClick =() =>{
    logingWithFacebook().then(user=>{
      console.log(user);
    }).catch(error =>{
      console.log(error);
    })
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <AppLayout>
                        
                <section>

                    <img src='/football.png.png' alt='webSite logo' />

                    <h1> Next-Football </h1>
                    <h2>Waiting for Qatar ⚽</h2>
                    <div>
                      <Button onClick={handleLoginClick}>
                          <GitHubIcon fill="white" width={27} height={27}/>
                          Loging with Facebook
                      </Button>
                    </div>

                  
                </section>

      </AppLayout>

      <style jsx>{`

          section{
            display: grid;
            place-content: center;
            place-items:center;
            height:100%
          }

          div{
            margin:0.8rem
          }

          img {
            width: 7.5em;
          }

          h1{
            color:${colors.primary};
            font-size: 2rem;
            font-weight:800;
            margin-bottom: 0.1rem

          }

          h2{
            color:${colors.secundary};
            font-size: 1.5rem;
            margin-bottom: 0.2rem
          }
      `}
      </style>
    
         
        
       
    </>
  )
}
